spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=True&serverTimezone=UTC
    username: root
    password: '468291'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
